# Generated by Django 4.2 on 2023-11-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Complete'), (2, 'Intermediate Recommendation'), (3, 'Intermediate Question')])),
            ],
        ),
        migrations.CreateModel(
            name='AttrValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(verbose_name=255)),
                ('attr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.attr')),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.case')),
            ],
        ),
    ]
