# Generated by Django 4.2 on 2023-11-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_case_create_date_case_name_case_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='create_date',
            field=models.DateTimeField(blank=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='update_date',
            field=models.DateTimeField(blank=True, verbose_name='Updated on'),
        ),
    ]
