# Generated by Django 4.2 on 2023-11-25 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_attrvalue_attr_id_alter_attrvalue_case_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attrvalue',
            name='attr_id',
        ),
        migrations.RemoveField(
            model_name='attrvalue',
            name='case_id',
        ),
        migrations.AddField(
            model_name='attrvalue',
            name='attr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='core.attr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attrvalue',
            name='case',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='core.case'),
            preserve_default=False,
        ),
    ]
