# Generated by Django 4.2 on 2023-11-26 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_attrvalue_is_any'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attr',
            options={'verbose_name': 'Атрибут', 'verbose_name_plural': 'Атрибуты'},
        ),
        migrations.AlterModelOptions(
            name='attrvalue',
            options={'verbose_name': 'Значение атрибута', 'verbose_name_plural': 'Значения атрибута'},
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Кейс', 'verbose_name_plural': 'Кейсы'},
        ),
        migrations.AlterField(
            model_name='attr',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='attr',
            name='priority',
            field=models.IntegerField(verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='attr',
            name='question',
            field=models.TextField(blank=True, verbose_name='Задаваемый пользователю вопрос'),
        ),
        migrations.AlterField(
            model_name='attrvalue',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='core.attr', verbose_name='Атрибут'),
        ),
        migrations.AlterField(
            model_name='attrvalue',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='core.case', verbose_name='Кейс'),
        ),
        migrations.AlterField(
            model_name='attrvalue',
            name='is_any',
            field=models.BooleanField(default=False, verbose_name='Нестрогое сравнение'),
        ),
        migrations.AlterField(
            model_name='attrvalue',
            name='value',
            field=models.CharField(blank=True, max_length=255, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='case',
            name='create_date',
            field=models.DateTimeField(blank=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='case',
            name='recommendation',
            field=models.TextField(blank=True, verbose_name='Тест рекомендации в MARKDOWN'),
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.IntegerField(choices=[(1, 'Complete'), (2, 'Intermediate Recommendation'), (3, 'Intermediate Question')], verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='case',
            name='update_date',
            field=models.DateTimeField(blank=True, verbose_name='Дата обновления'),
        ),
    ]
