# Generated by Django 4.2 on 2023-11-26 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_attr_options_alter_attrvalue_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Тело заявки')),
                ('create_date', models.DateTimeField(blank=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(blank=True, verbose_name='Дата обновления')),
                ('user_name', models.CharField(max_length=255, verbose_name='Имя заявителя')),
                ('email', models.CharField(max_length=255, verbose_name='Email заявителя')),
                ('additional_contacts', models.CharField(max_length=255, verbose_name='Контакты заявителя')),
                ('files', models.TextField(verbose_name='Приложенные файлы')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
        migrations.CreateModel(
            name='RequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Адрес файла')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_urls', to='core.request', verbose_name='Запрос')),
            ],
        ),
        migrations.CreateModel(
            name='RequestAttr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Значение')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='core.request', verbose_name='Запрос')),
            ],
        ),
    ]
